const fs = require('fs');
const data = JSON.parse(fs.readFileSync(process.env.TEMP + '/t5_list.json', 'utf8'));
console.log('\n=== CLI list --json: Skills Analysis ===');
console.log('Total skills:', data.length);
console.log('\nAll slugs:');
data.forEach((s, i) => console.log(`  ${i+1}. ${s.slug.padEnd(45)} [${s.category}] verified:${s.verified} source:${s.source} downloads:${s.downloads||0}`));
console.log('\nBy source:');
const bySrc = {};
data.forEach(s => { bySrc[s.source] = (bySrc[s.source] || 0) + 1; });
Object.entries(bySrc).forEach(([src, count]) => console.log(`  ${src}: ${count}`));
