// Bloco 5/5 — SECURITY (50 skills únicas)
const SUPABASE_URL = 'https://liqutcjzzrqstivvfele.supabase.co';
const SUPABASE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxpcXV0Y2p6enJxc3RpdnZmZWxlIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3NTQ5ODAzNiwiZXhwIjoyMDkxMDc0MDM2fQ.CEwxEeOB2CoAF0JyreovFYhU4Ibc03np8RgU6B6SiP0';

async function fetchExistingSlugs() {
  const res = await fetch(`${SUPABASE_URL}/rest/v1/skills?select=slug`, {
    headers: { 'apikey': SUPABASE_KEY, 'Authorization': `Bearer ${SUPABASE_KEY}` }
  });
  const data = await res.json();
  return new Set(data.map(s => s.slug));
}

async function insertSkills(skills, blockName) {
  const existingSlugs = await fetchExistingSlugs();
  const conflicts = skills.filter(s => existingSlugs.has(s.slug));
  if (conflicts.length > 0) { console.error(`❌ CONFLICTS in ${blockName} (${conflicts.length}):`); conflicts.forEach(s => console.error(`   - ${s.slug}`)); process.exit(1); }
  console.log(`✅ No slug conflicts for ${blockName}.\n`);
  let inserted = 0, skipped = 0;
  for (let i = 0; i < skills.length; i += 10) {
    const batch = skills.slice(i, i + 10);
    const res = await fetch(`${SUPABASE_URL}/rest/v1/skills`, { method: 'POST', headers: { 'apikey': SUPABASE_KEY, 'Authorization': `Bearer ${SUPABASE_KEY}`, 'Content-Type': 'application/json', 'Prefer': 'resolution=merge-duplicates' }, body: JSON.stringify(batch) });
    if (res.ok || res.status === 201) { inserted += batch.length; console.log(`  ✅ Batch ${Math.floor(i/10)+1}: ${batch.length} skills inserted`); }
    else { let bi = 0; for (const skill of batch) { const r = await fetch(`${SUPABASE_URL}/rest/v1/skills`, { method: 'POST', headers: { 'apikey': SUPABASE_KEY, 'Authorization': `Bearer ${SUPABASE_KEY}`, 'Content-Type': 'application/json', 'Prefer': 'resolution=merge-duplicates' }, body: JSON.stringify([skill]) }); if (r.ok || r.status === 201) bi++; else skipped++; } inserted += bi; console.log(`  ⚠️  Batch ${Math.floor(i/10)+1}: ${bi} inserted, ${batch.length - bi} skipped`); }
  }
  console.log(`\n=== ${blockName} RESULT ===`);
  console.log(`Total attempted: ${skills.length}`);
  console.log(`Total inserted: ${inserted}`);
  console.log(`Total skipped: ${skipped}`);
}

const block5 = [
  {id:'cybersecurity_specialist',name:'Cybersecurity Specialist',slug:'cybersecurity-specialist',description:'Avalia postura de segurança com frameworks NIST, ISO 27001 e CIS Controls.',long_description:'Especialista em cybersecurity que avalia maturidade de segurança usando frameworks NIST CSF, ISO 27001 e CIS Controls v8. Identifica gaps, prioriza remediation por risco, gera roadmap de implementação e relatórios executivos para board.',category:'security',tags:['cybersecurity','nist','iso27001','cis','framework'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.96,install_command:'npx aifeast cybersecurity-specialist',run_command:'npx aifeast run cybersecurity-specialist'},
  {id:'ethical_hacker',name:'Ethical Hacker',slug:'ethical-hacker',description:'Simula ataques éticos com reconhecimento, exploração e relatórios.',long_description:'Hacker ético que conduz penetration tests estruturados: reconhecimento (OSINT, scanning), exploração (vulnerabilidades conhecidas, misconfigurations), pós-exploração (lateral movement, privilege escalation) e gera relatórios com evidências e remediação.',category:'security',tags:['pentest','ethical-hacking','exploitation','osint','recon'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.95,install_command:'npx aifeast ethical-hacker',run_command:'npx aifeast run ethical-hacker'},
  {id:'penetration_tester',name:'Penetration Tester',slug:'penetration-tester',description:'Testa aplicações web com OWASP Top 10, API security e auth bypass.',long_description:'Tester de penetração focado em aplicações web que testa OWASP Top 10 (injection, broken auth, XSS, IDOR, SSRF), explora APIs (GraphQL, REST), testa bypass de autenticação, session management e gera relatórios com PoCs e fixes.',category:'security',tags:['web-security','owasp','api','auth','injection'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.95,install_command:'npx aifeast penetration-tester',run_command:'npx aifeast run penetration-tester'},
  {id:'compliance_officer',name:'Compliance Officer',slug:'compliance-officer',description:'Verifica conformidade com LGPD, GDPR, PCI-DSS e regulamentações setoriais.',long_description:'Officer de compliance que audita sistemas contra LGPD, GDPR, PCI-DSS, HIPAA e regulamentações setoriais. Mapeia dados pessoais, verifica bases legais, avalia transferências internacionais, gera DPIAs e relatórios de conformidade.',category:'security',tags:['compliance','lgpd','gdpr','pci-dss','regulations'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.95,install_command:'npx aifeast compliance-officer',run_command:'npx aifeast run compliance-officer'},
  {id:'privacy_advisor',name:'Privacy Advisor',slug:'privacy-advisor',description:'Aconselha sobre privacidade de dados, consentimento e direitos do titular.',long_description:'Conselheiro de privacidade que avalia práticas de coleta de dados, verifica consentimento válido, mapeia fluxos de dados, implementa direitos do titular (acesso, retificação, exclusão), configura privacy by design e gera políticas de privacidade.',category:'security',tags:['privacy','consent','data-rights','lgpd','by-design'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.94,install_command:'npx aifeast privacy-advisor',run_command:'npx aifeast run privacy-advisor'},
  {id:'threat_modeler',name:'Threat Modeler',slug:'threat-modeler',description:'Modela ameaças com STRIDE, DREAD e attack trees para sistemas.',long_description:'Modelador de ameaças que aplica metodologias STRIDE (Spoofing, Tampering, Repudiation, Information Disclosure, DoS, Elevation), DREAD scoring, constrói attack trees, identifica trust boundaries e gera matrizes de risco com mitigações.',category:'security',tags:['threat-modeling','stride','attack-trees','risk','mitigation'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.95,install_command:'npx aifeast threat-modeler',run_command:'npx aifeast run threat-modeler'},
  {id:'incident_responder',name:'Incident Responder',slug:'incident-responder',description:'Responde a incidentes de segurança com contenção, erradicação e recovery.',long_description:'Respondedor de incidentes que segue framework NIST SP 800-61: preparação, detecção, análise, contenção, erradicação, recovery e lessons learned. Gera timelines de incidente, preserva evidências forenses e produz relatórios pós-incidente.',category:'security',tags:['incident-response','containment','forensics','recovery','nist'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.95,install_command:'npx aifeast incident-responder',run_command:'npx aifeast run incident-responder'},
  {id:'malware_analyst',name:'Malware Analyst',slug:'malware-analyst',description:'Analisa malware com sandboxing, reverse engineering e IoC extraction.',long_description:'Analisador de malware que executa samples em sandbox isolado, analisa comportamento (processos, rede, registry), extrai Indicators of Compromise (IoCs), faz reverse engineering básico de binários e gera relatórios de ameaça com TTPs MITRE ATT&CK.',category:'security',tags:['malware','sandbox','reverse-engineering','ioc','mitre'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.94,install_command:'npx aifeast malware-analyst',run_command:'npx aifeast run malware-analyst'},
  {id:'cryptography_expert',name:'Cryptography Expert',slug:'cryptography-expert',description:'Avalia implementações criptográficas com algoritmos, chaves e protocols.',long_description:'Especialista em criptografia que avalia uso de algoritmos (AES, RSA, ECC, SHA), verifica gestão de chaves (geração, rotação, destruição), analisa protocols TLS/SSL, detecta uso de crypto fraco ou deprecated e sugere upgrades.',category:'security',tags:['cryptography','encryption','tls','keys','algorithms'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.95,install_command:'npx aifeast cryptography-expert',run_command:'npx aifeast run cryptography-expert'},
  {id:'secret_scanner_pro',name:'Secret Scanner Pro',slug:'secret-scanner-pro',description:'Escaneia repositórios em busca de secrets expostos com 50+ patterns.',long_description:'Scanner de secrets que detecta API keys, tokens, senhas hardcoded, certificados, chaves privadas em 50+ padrões (AWS, GitHub, Stripe, Slack, JWT). Suporta scan de Git history, gera relatórios com localização exata e sugere remediação imediata.',category:'security',tags:['secrets','api-keys','tokens','git-history','scanning'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.96,install_command:'npx aifeast secret-scanner-pro',run_command:'npx aifeast run secret-scanner-pro'},
  {id:'dependency_auditor_pro',name:'Dependency Auditor Pro',slug:'dependency-auditor-pro',description:'Audita dependências com CVEs, licenças e sugestões de upgrade seguro.',long_description:'Auditor de dependências que escaneia package.json, requirements.txt, Gemfile, go.mod em busca de CVEs conhecidos, verifica licenças compatíveis, identifica pacotes abandonados, sugere upgrades seguros e gera relatório por severidade.',category:'security',tags:['dependencies','cve','licenses','upgrades','audit'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.95,install_command:'npx aifeast dependency-auditor-pro',run_command:'npx aifeast run dependency-auditor-pro'},
  {id:'cve_checker',name:'CVE Checker',slug:'cve-checker',description:'Verifica vulnerabilidades CVE em software e sistemas com score CVSS.',long_description:'Checker de CVEs que consulta bases NVD, GitHub Advisory e Snyk, identifica vulnerabilidades afetando o stack tecnológico, calcula score CVSS v3.1, prioriza por exploitabilidade e gera relatórios com patches disponíveis.',category:'security',tags:['cve','cvss','nvd','vulnerabilities','patching'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.94,install_command:'npx aifeast cve-checker',run_command:'npx aifeast run cve-checker'},
  {id:'ssl_validator',name:'SSL Validator',slug:'ssl-validator',description:'Valida certificados SSL/TLS com chain of trust, expiry e cipher suites.',long_description:'Validador de SSL/TLS que verifica chain of trust completa, datas de expiração, cipher suites configuradas, protocolo versions (TLS 1.2/1.3), HSTS headers, certificate transparency logs e gera relatório com grading (A+ a F).',category:'security',tags:['ssl','tls','certificates','ciphers','validation'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.93,install_command:'npx aifeast ssl-validator',run_command:'npx aifeast run ssl-validator'},
  {id:'header_analyzer',name:'Header Analyzer',slug:'header-analyzer',description:'Analisa HTTP security headers com CSP, HSTS, X-Frame-Options e mais.',long_description:'Analisador de headers HTTP que verifica security headers (CSP, HSTS, X-Frame-Options, X-Content-Type-Options, Referrer-Policy, Permissions-Policy), identifica ausências e misconfigurations, sugere valores seguros e testa impacto de CSP policies.',category:'security',tags:['headers','csp','hsts','security','http'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.93,install_command:'npx aifeast header-analyzer',run_command:'npx aifeast run header-analyzer'},
  {id:'port_scanner',name:'Port Scanner',slug:'port-scanner',description:'Escaneia portas abertas com identificação de serviços e versões.',long_description:'Scanner de portas que identifica portas abertas, serviços rodando, versões de software, detecta firewalls/IDS, classifica risco de cada serviço exposto e gera relatório com recomendações de hardening (fechar portas desnecessárias, atualizar versões).',category:'security',tags:['ports','scanning','services','firewall','hardening'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.93,install_command:'npx aifeast port-scanner',run_command:'npx aifeast run port-scanner'},
  {id:'permission_auditor',name:'Permission Auditor',slug:'permission-auditor',description:'Audita permissões de IAM, RBAC e acesso com princípio do menor privilégio.',long_description:'Auditor de permissões que analisa políticas IAM (AWS, GCP, Azure), RBAC em aplicações, identifica over-privileged accounts, verifica separação de duties, detecta credenciais não rotacionadas e sugere políticas de least privilege.',category:'security',tags:['iam','rbac','permissions','least-privilege','audit'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.94,install_command:'npx aifeast permission-auditor',run_command:'npx aifeast run permission-auditor'},
  {id:'config_validator',name:'Config Validator',slug:'config-validator',description:'Valida configurações de segurança em cloud, containers e aplicações.',long_description:'Validador de configurações que verifica security configs de cloud (S3 buckets públicos, security groups permissivos), containers (root user, capabilities), aplicações (debug mode, verbose errors) e gera relatório com severidade e remediation.',category:'security',tags:['configuration','validation','cloud','containers','hardening'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.93,install_command:'npx aifeast config-validator',run_command:'npx aifeast run config-validator'},
  {id:'certificate_monitor',name:'Certificate Monitor',slug:'certificate-monitor',description:'Monitora certificados SSL com alertas de expiração e auto-renovação.',long_description:'Monitor de certificados que rastreia todos os SSL/TLS certificados do ambiente, alerta 30/14/7 dias antes da expiração, verifica certificate transparency logs, detecta certificados não autorizados e integra com Let\'s Encrypt para auto-renovação.',category:'security',tags:['certificates','monitoring','expiry','renewal','transparency'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.93,install_command:'npx aifeast certificate-monitor',run_command:'npx aifeast run certificate-monitor'},
  {id:'firewall_rule_checker',name:'Firewall Rule Checker',slug:'firewall-rule-checker',description:'Analisa regras de firewall com redundâncias, conflitos e overly permissive rules.',long_description:'Checker de firewall que analisa rule sets (iptables, AWS SG, GCP firewall), identifica regras redundantes, conflitos entre regras, rules overly permissive (0.0.0.0/0), sugere otimizações e gera documentação visual do fluxo de tráfego.',category:'security',tags:['firewall','rules','analysis','optimization','traffic'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.93,install_command:'npx aifeast firewall-rule-checker',run_command:'npx aifeast run firewall-rule-checker'},
  {id:'owasp_checker',name:'OWASP Checker',slug:'owasp-checker',description:'Verifica conformidade com OWASP Top 10 e ASVS em aplicações web.',long_description:'Checker OWASP que testa aplicações contra OWASP Top 10 (Injection, Broken Auth, Sensitive Data Exposure, XXE, Broken Access Control, Security Misconfiguration, XSS, Insecure Deserialization, Known Vulnerabilities, Insufficient Logging) e OWASP ASVS.',category:'security',tags:['owasp','top10','asvs','web-security','compliance'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.95,install_command:'npx aifeast owasp-checker',run_command:'npx aifeast run owasp-checker'},
  {id:'sast_analyzer',name:'SAST Analyzer',slug:'sast-analyzer',description:'Análise estática de código com detecção de vulnerabilidades em múltiplas linguagens.',long_description:'Analisador SAST que escaneia código-fonte (Python, JS, Java, Go, C#) para vulnerabilidades (SQL injection, XSS, path traversal, command injection, hardcoded secrets), gera relatórios com linha exata, severity e código de correção.',category:'security',tags:['sast','static-analysis','vulnerabilities','code-scanning','security'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.95,install_command:'npx aifeast sast-analyzer',run_command:'npx aifeast run sast-analyzer'},
  {id:'dast_tester',name:'DAST Tester',slug:'dast-tester',description:'Testes dinâmicos de segurança em aplicações rodando com crawling e fuzzing.',long_description:'Tester DAST que analisa aplicações em execução, crawla todas as páginas e endpoints, fuzz inputs para encontrar vulnerabilidades, testa autenticação e session management, verifica error handling e gera relatórios com PoCs reproduzíveis.',category:'security',tags:['dast','dynamic-testing','crawling','fuzzing','runtime'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.94,install_command:'npx aifeast dast-tester',run_command:'npx aifeast run dast-tester'},
  {id:'supply_chain_auditor',name:'Supply Chain Auditor',slug:'supply-chain-auditor',description:'Audita cadeia de suprimentos de software com SBOM e verificação de integridade.',long_description:'Auditor de supply chain que gera Software Bill of Materials (SBOM), verifica integridade de pacotes (checksums, signatures), detecta dependency confusion attacks, analisa maintainer reputation e monitora compromissos de pacotes upstream.',category:'security',tags:['supply-chain','sbom','integrity','packages','upstream'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.95,install_command:'npx aifeast supply-chain-auditor',run_command:'npx aifeast run supply-chain-auditor'},
  {id:'container_security_scanner',name:'Container Security Scanner',slug:'container-security-scanner',description:'Escaneia imagens Docker com CVEs, misconfigurations e best practices.',long_description:'Scanner de containers que analisa imagens Docker para CVEs em layers, verifica misconfigurations (running as root, excessive capabilities, missing health checks), aplica benchmarks CIS Docker e gera relatórios com severidade e fixes.',category:'security',tags:['containers','docker','cve','misconfiguration','cis'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.94,install_command:'npx aifeast container-security-scanner',run_command:'npx aifeast run container-security-scanner'},
  {id:'iam_policy_reviewer',name:'IAM Policy Reviewer',slug:'iam-policy-reviewer',description:'Revisa políticas IAM na cloud com análise de permissões excessivas.',long_description:'Reviewer de políticas IAM que analisa JSON policies de AWS/GCP/Azure, identifica wildcard permissions (*), verifica acesso cross-account, detecta credenciais de longa duração, sugere políticas granulares e aplica princípio de least privilege.',category:'security',tags:['iam','policies','cloud','permissions','least-privilege'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.94,install_command:'npx aifeast iam-policy-reviewer',run_command:'npx aifeast run iam-policy-reviewer'},
  {id:'network_topology_analyzer',name:'Network Topology Analyzer',slug:'network-topology-analyzer',description:'Analisa topologia de rede com segmentação, zonas de trust e surface de ataque.',long_description:'Analisador de topologia de rede que mapeia subnets, security groups, VPCs, load balancers, identifica zonas de trust, avalia segmentação de rede, calcula superfície de ataque externa e sugere micro-segmentação.',category:'security',tags:['network','topology','segmentation','vpc','attack-surface'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.93,install_command:'npx aifeast network-topology-analyzer',run_command:'npx aifeast run network-topology-analyzer'},
  {id:'log_forensics',name:'Log Forensics',slug:'log-forensics',description:'Investiga logs para reconstruir timelines de ataques e atividade maliciosa.',long_description:'Forense de logs que analisa logs de sistema, aplicação e rede, reconstrói timelines de incidentes, correlaciona eventos de múltiplas fontes, identifica IOCs (Indicators of Compromise), detecta lateral movement e gera relatórios forenses para legal.',category:'security',tags:['forensics','logs','timeline','investigation','ioc'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.94,install_command:'npx aifeast log-forensics',run_command:'npx aifeast run log-forensics'},
  {id:'incident_timeline_builder',name:'Incident Timeline Builder',slug:'incident-timeline-builder',description:'Constrói timelines detalhados de incidentes de segurança com evidências.',long_description:'Construtor de timelines de incidentes que agrega logs, alerts e ações de resposta em timeline visual, identifica primeiro ponto de comprometimento, mapeia movimentação do atacante, documenta ações de resposta e gera relatório para stakeholders.',category:'security',tags:['timeline','incident','evidence','response','documentation'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.93,install_command:'npx aifeast incident-timeline-builder',run_command:'npx aifeast run incident-timeline-builder'},
  {id:'risk_assessment_matrix',name:'Risk Assessment Matrix',slug:'risk-assessment-matrix',description:'Gera matrizes de risco com probabilidade, impacto e planos de mitigação.',long_description:'Gerador de matrizes de risco que identifica ameaças, avalia probabilidade e impacto (1-5), calcula risk score, prioriza por criticidade, sugere planos de mitigação com custos estimados e gera heat maps visuais para apresentação.',category:'security',tags:['risk','matrix','probability','impact','mitigation'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.94,install_command:'npx aifeast risk-assessment-matrix',run_command:'npx aifeast run risk-assessment-matrix'},
  {id:'prompt_injection_detector',name:'Prompt Injection Detector',slug:'prompt-injection-detector',description:'Detecta tentativas de prompt injection e jailbreak em inputs de LLM.',long_description:'Detector de prompt injection que analisa inputs de usuários para tentativas de manipulação de LLM (prompt injection, jailbreak, role-playing attacks), classifica severidade, bloqueia inputs maliciosos e gera logs de tentativas.',category:'security',tags:['prompt-injection','jailbreak','llm-security','manipulation','detection'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.95,install_command:'npx aifeast prompt-injection-detector',run_command:'npx aifeast run prompt-injection-detector'},
  {id:'content_filter',name:'Content Filter',slug:'content-filter',description:'Filtra conteúdo malicioso: malware links, phishing e dados sensíveis.',long_description:'Filtro de conteúdo que escaneia textos e URLs para links maliciosos, tentativas de phishing, vazamento de dados sensíveis (PII, credenciais), conteúdo tóxico e aplica políticas de conteúdo customizáveis com whitelist/blacklist.',category:'security',tags:['content','filter','phishing','malware','pii'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.93,install_command:'npx aifeast content-filter',run_command:'npx aifeast run content-filter'},
  {id:'pii_redactor',name:'PII Redactor',slug:'pii-redactor',description:'Detecta e mascara dados pessoais (PII) em textos, logs e documentos.',long_description:'Redator de PII que detecta dados pessoais sensíveis (CPF, email, telefone, endereço, cartão de crédito), mascara ou substitui por tokens, verifica compliance com LGPD/GDPR, gera relatórios de detecção e mantém audit trail de redações.',category:'security',tags:['pii','redaction','privacy','lgpd','tokenization'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.95,install_command:'npx aifeast pii-redactor',run_command:'npx aifeast run pii-redactor'},
  {id:'toxicity_classifier',name:'Toxicity Classifier',slug:'toxicity-classifier',description:'Classifica toxicidade de textos com detecção de hate speech e harassment.',long_description:'Classificador de toxicidade que analisa textos para hate speech, harassment, self-harm, sexual content, violence e insultos. Gera scores por categoria, sugere ações (bloquear, revisar, warning) e permite customização de thresholds por comunidade.',category:'security',tags:['toxicity','hate-speech','harassment','moderation','classification'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.93,install_command:'npx aifeast toxicity-classifier',run_command:'npx aifeast run toxicity-classifier'},
  {id:'jailbreak_detector',name:'Jailbreak Detector',slug:'jailbreak-detector',description:'Detecta técnicas de jailbreak em prompts com padrões conhecidos e anomalias.',long_description:'Detector de jailbreak que identifica técnicas conhecidas (DAN, role-play, hypothetical scenarios, encoding attacks), analisa padrões de anomalia em prompts, classifica nível de sofisticação do ataque, bloqueia tentativas e gera relatórios de tentativas.',category:'security',tags:['jailbreak','detection','prompt-security','attacks','defense'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.94,install_command:'npx aifeast jailbreak-detector',run_command:'npx aifeast run jailbreak-detector'},
  {id:'hallucination_checker',name:'Hallucination Checker',slug:'hallucination-checker',description:'Verifica facticidade de outputs de LLM com validação cruzada de fontes.',long_description:'Checker de alucinações que compara outputs de LLM com fontes verificáveis, identifica afirmações sem suporte, detecta contradições internas, calcula score de confiabilidade e sugere verificações factuais para claims suspeitos.',category:'security',tags:['hallucination','fact-checking','verification','llm','reliability'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.93,install_command:'npx aifeast hallucination-checker',run_command:'npx aifeast run hallucination-checker'},
  {id:'fact_verifier',name:'Fact Verifier',slug:'fact-verifier',description:'Verifica fatos em textos com busca em fontes confiáveis e cross-reference.',long_description:'Verificador de fatos que extrai claims de textos, busca em fontes confiáveis (Wikipedia, bases acadêmicas, sites oficiais), cross-referencia informações, classifica veracidade (verdadeiro, falso, impreciso, insuficiente) e cita fontes.',category:'security',tags:['fact-checking','verification','sources','cross-reference','claims'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.93,install_command:'npx aifeast fact-verifier',run_command:'npx aifeast run fact-verifier'},
  {id:'source_validator',name:'Source Validator',slug:'source-validator',description:'Valida credibilidade de fontes com análise de domínio, autoria e viés.',long_description:'Validador de fontes que analisa credibilidade de websites e publicações, verifica domínio age e reputação, identifica viés editorial, detecta fake news patterns, verifica autoria e gera score de confiabilidade por fonte.',category:'security',tags:['sources','validation','credibility','bias','fake-news'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.92,install_command:'npx aifeast source-validator',run_command:'npx aifeast run source-validator'},
  {id:'auth_flow_auditor',name:'Auth Flow Auditor',slug:'auth-flow-auditor',description:'Audita fluxos de autenticação com OAuth, JWT, MFA e session management.',long_description:'Auditor de autenticação que analisa implementações de OAuth2/OIDC, verifica JWT configuration (algoritmo, expiry, claims), testa MFA enforcement, analisa session management (fixation, hijacking) e gera relatório com vulnerabilidades e fixes.',category:'security',tags:['auth','oauth','jwt','mfa','sessions'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.95,install_command:'npx aifeast auth-flow-auditor',run_command:'npx aifeast run auth-flow-auditor'},
  {id:'session_manager',name:'Session Manager',slug:'session-manager',description:'Gerencia sessões com secure cookies, timeout e proteção contra hijacking.',long_description:'Gerenciador de sessões que implementa secure cookies (HttpOnly, Secure, SameSite), configura timeouts automáticos, detecta session hijacking (IP change, user agent change), implementa session rotation após login e invalidação em logout.',category:'security',tags:['sessions','cookies','hijacking','timeout','rotation'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.94,install_command:'npx aifeast session-manager',run_command:'npx aifeast run session-manager'},
  {id:'token_validator',name:'Token Validator',slug:'token-validator',description:'Valida tokens JWT/OAuth com verificação de signature, expiry e claims.',long_description:'Validador de tokens que verifica signatures JWT (RS256, ES256), checa expiry/iat/nbf claims, valida audience e issuer, detecta token replay, implementa token blacklist e gera logs de validação com motivo de rejeição.',category:'security',tags:['tokens','jwt','validation','claims','blacklist'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.94,install_command:'npx aifeast token-validator',run_command:'npx aifeast run token-validator'},
  {id:'rate_limit_enforcer',name:'Rate Limit Enforcer',slug:'rate-limit-enforcer',description:'Aplica rate limiting com estratégias adaptativas por tipo de endpoint.',long_description:'Enforcer de rate limiting que aplica limites por tipo de endpoint (auth: 5/min, API: 100/min, uploads: 10/h), usa sliding window com Redis, retorna headers X-RateLimit, implementa progressive throttling e bloqueio temporário de offenders.',category:'security',tags:['rate-limiting','throttling','adaptive','redis','protection'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.93,install_command:'npx aifeast rate-limit-enforcer',run_command:'npx aifeast run rate-limit-enforcer'},
  {id:'input_sanitizer',name:'Input Sanitizer',slug:'input-sanitizer',description:'Sanitiza inputs de usuário contra XSS, injection e encoding attacks.',long_description:'Sanitizador de inputs que limpa inputs de usuário contra XSS, SQL injection, command injection, path traversal, XXE e encoding attacks. Aplica allowlist de caracteres, escape contextual, valida schema e rejeita inputs malformados.',category:'security',tags:['sanitization','xss','injection','encoding','validation'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.95,install_command:'npx aifeast input-sanitizer',run_command:'npx aifeast run input-sanitizer'},
  {id:'output_validator',name:'Output Validator',slug:'output-validator',description:'Valida outputs de APIs e LLMs contra data leakage e conteúdo inseguro.',long_description:'Validador de outputs que verifica APIs e respostas de LLM para data leakage (PII, credentials, internal info), conteúdo inseguro, formatação maliciosa e conformidade com políticas. Intercepta outputs problemáticos antes do delivery.',category:'security',tags:['output','validation','leakage','policies','interception'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.94,install_command:'npx aifeast output-validator',run_command:'npx aifeast run output-validator'},
  {id:'encryption_manager',name:'Encryption Manager',slug:'encryption-manager',description:'Gerencia criptografia de dados em trânsito e repouso com key rotation.',long_description:'Gerenciador de criptografia que implementa AES-256 para data at rest, TLS 1.3 para data in transit, gerencia lifecycle de chaves (geração, rotação automática, destruição), aplica envelope encryption e integra com KMS (AWS, GCP, HashiCorp Vault).',category:'security',tags:['encryption','aes','tls','key-management','kms'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.95,install_command:'npx aifeast encryption-manager',run_command:'npx aifeast run encryption-manager'},
  {id:'key_rotation_handler',name:'Key Rotation Handler',slug:'key-rotation-handler',description:'Automatiza rotação de chaves API, certificados e secrets com zero downtime.',long_description:'Handler de rotação de chaves que automatiza rotação de API keys, certificados SSL, database credentials e secrets, implementa dual-key overlap para zero downtime, notifica stakeholders antes da expiração e mantém audit trail completo.',category:'security',tags:['key-rotation','automation','zero-downtime','secrets','lifecycle'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.94,install_command:'npx aifeast key-rotation-handler',run_command:'npx aifeast run key-rotation-handler'},
  {id:'rbac_enforcer',name:'RBAC Enforcer',slug:'rbac-enforcer',description:'Implementa e audita controle de acesso baseado em roles com least privilege.',long_description:'Enforcer de RBAC que define roles e permissões granulares, aplica princípio de least privilege, implementa separação de duties, audita acessos em tempo real, detecta privilege creep e gera relatórios de conformidade de acesso.',category:'security',tags:['rbac','access-control','least-privilege','roles','audit'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.94,install_command:'npx aifeast rbac-enforcer',run_command:'npx aifeast run rbac-enforcer'},
  {id:'security_headers_setter',name:'Security Headers Setter',slug:'security-headers-setter',description:'Configura security headers em servidores web com valores otimizados.',long_description:'Configurador de security headers que aplica Content-Security-Policy, Strict-Transport-Security, X-Content-Type-Options, X-Frame-Options, Referrer-Policy, Permissions-Policy com valores otimizados por tipo de aplicação e testa com securityheaders.com.',category:'security',tags:['headers','csp','hsts','configuration','hardening'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.93,install_command:'npx aifeast security-headers-setter',run_command:'npx aifeast run security-headers-setter'},
  {id:'zero_trust_architect',name:'Zero Trust Architect',slug:'zero-trust-architect',description:'Design de arquitetura Zero Trust com micro-segmentação e verificação contínua.',long_description:'Arquiteto Zero Trust que design implementações com never trust always verify, micro-segmentação de rede, verificação contínua de identity/device, least privilege access, encrypted communications e monitoring contínuo de anomalias.',category:'security',tags:['zero-trust','micro-segmentation','identity','verification','architecture'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.96,install_command:'npx aifeast zero-trust-architect',run_command:'npx aifeast run zero-trust-architect'}
];

console.log(`\n=== BLOCO 5/5 — SECURITY (${block5.length} skills) ===`);
await insertSkills(block5, 'BLOCK 5: SECURITY');
