// Bloco 4/5 — ANALYSIS (50 skills únicas)
const SUPABASE_URL = 'https://liqutcjzzrqstivvfele.supabase.co';
const SUPABASE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxpcXV0Y2p6enJxc3RpdnZmZWxlIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3NTQ5ODAzNiwiZXhwIjoyMDkxMDc0MDM2fQ.CEwxEeOB2CoAF0JyreovFYhU4Ibc03np8RgU6B6SiP0';

async function fetchExistingSlugs() {
  const res = await fetch(`${SUPABASE_URL}/rest/v1/skills?select=slug`, {
    headers: { 'apikey': SUPABASE_KEY, 'Authorization': `Bearer ${SUPABASE_KEY}` }
  });
  const data = await res.json();
  return new Set(data.map(s => s.slug));
}

async function insertSkills(skills, blockName) {
  const existingSlugs = await fetchExistingSlugs();
  const conflicts = skills.filter(s => existingSlugs.has(s.slug));
  if (conflicts.length > 0) {
    console.error(`❌ CONFLICTS in ${blockName} (${conflicts.length}):`);
    conflicts.forEach(s => console.error(`   - ${s.slug}`));
    process.exit(1);
  }
  console.log(`✅ No slug conflicts for ${blockName}.\n`);

  let inserted = 0, skipped = 0;
  for (let i = 0; i < skills.length; i += 10) {
    const batch = skills.slice(i, i + 10);
    const res = await fetch(`${SUPABASE_URL}/rest/v1/skills`, {
      method: 'POST',
      headers: { 'apikey': SUPABASE_KEY, 'Authorization': `Bearer ${SUPABASE_KEY}`, 'Content-Type': 'application/json', 'Prefer': 'resolution=merge-duplicates' },
      body: JSON.stringify(batch)
    });
    if (res.ok || res.status === 201) { inserted += batch.length; console.log(`  ✅ Batch ${Math.floor(i/10)+1}: ${batch.length} skills inserted`); }
    else {
      let bi = 0;
      for (const skill of batch) {
        const r = await fetch(`${SUPABASE_URL}/rest/v1/skills`, { method: 'POST', headers: { 'apikey': SUPABASE_KEY, 'Authorization': `Bearer ${SUPABASE_KEY}`, 'Content-Type': 'application/json', 'Prefer': 'resolution=merge-duplicates' }, body: JSON.stringify([skill]) });
        if (r.ok || r.status === 201) bi++; else skipped++;
      }
      inserted += bi;
      console.log(`  ⚠️  Batch ${Math.floor(i/10)+1}: ${bi} inserted, ${batch.length - bi} skipped`);
    }
  }
  console.log(`\n=== ${blockName} RESULT ===`);
  console.log(`Total attempted: ${skills.length}`);
  console.log(`Total inserted: ${inserted}`);
  console.log(`Total skipped: ${skipped}`);
}

const block4 = [
  {id:'business_analyst',name:'Business Analyst',slug:'business-analyst',description:'Analisa modelos de negócio, métricas financeiras e oportunidades de mercado.',long_description:'Analista de negócios que avalia viabilidade de modelos de negócio, calcula métricas financeiras (CAC, LTV, churn, burn rate), analisa TAM/SAM/SOM, identifica oportunidades de mercado e gera relatórios executivos para decisores.',category:'analysis',tags:['business','finance','metrics','market','strategy'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.94,install_command:'npx aifeast business-analyst',run_command:'npx aifeast run business-analyst'},
  {id:'data_analyst_pro',name:'Data Analyst Pro',slug:'data-analyst-pro',description:'Analisa datasets com estatística descritiva, correlações e visualizações.',long_description:'Analista de dados que processa datasets CSV/JSON/SQL, calcula estatísticas descritivas (média, mediana, desvio padrão), identifica correlações, detecta outliers, gera visualizações (histogramas, scatter plots, box plots) e insights acionáveis.',category:'analysis',tags:['data','statistics','correlation','visualization','insights'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.95,install_command:'npx aifeast data-analyst-pro',run_command:'npx aifeast run data-analyst-pro'},
  {id:'statistician',name:'Statistician',slug:'statistician',description:'Aplica testes estatísticos: t-test, ANOVA, chi-square e regressão.',long_description:'Estatístico que aplica testes de hipótese (t-test, ANOVA, chi-square, Mann-Whitney), calcula intervalos de confiança, ajusta modelos de regressão (linear, logística, polinomial), valida assumptions e interpreta p-values corretamente.',category:'analysis',tags:['statistics','hypothesis-testing','regression','anova','p-value'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.95,install_command:'npx aifeast statistician',run_command:'npx aifeast run statistician'},
  {id:'ml_engineer',name:'ML Engineer',slug:'ml-engineer',description:'Treina modelos de machine learning com seleção de features e validação cruzada.',long_description:'Engenheiro de ML que preprocessa dados, seleciona features relevantes, treina modelos (regressão, classificação, clustering), valida com cross-validation, otimiza hyperparâmetros e exporta modelos para produção com monitoring.',category:'analysis',tags:['ml','training','features','cross-validation','models'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.96,install_command:'npx aifeast ml-engineer',run_command:'npx aifeast run ml-engineer'},
  {id:'research_assistant',name:'Research Assistant',slug:'research-assistant',description:'Conduz pesquisas acadêmicas com revisão bibliográfica e síntese de papers.',long_description:'Assistente de pesquisa que busca papers em bases acadêmicas, sintetiza findings de múltiplos estudos, identifica gaps na literatura, gera revisões bibliográficas estruturadas e formata citações em APA/MLA/Chicago.',category:'analysis',tags:['research','academic','papers','literature-review','citations'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.93,install_command:'npx aifeast research-assistant',run_command:'npx aifeast run research-assistant'},
  {id:'trend_researcher',name:'Trend Researcher',slug:'trend-researcher',description:'Identifica tendências de mercado com análise de sinais fracos e dados sociais.',long_description:'Pesquisador de tendências que analisa sinais fracos em redes sociais, Google Trends, notícias e fóruns. Identifica padrões emergentes, projeta curvas de adoção, mapeia early adopters e gera relatórios de tendências com evidências quantitativas.',category:'analysis',tags:['trends','market','signals','social-media','forecasting'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.93,install_command:'npx aifeast trend-researcher',run_command:'npx aifeast run trend-researcher'},
  {id:'market_analyst',name:'Market Analyst',slug:'market-analyst',description:'Analisa mercados com dados de participação, crescimento e competitividade.',long_description:'Analista de mercado que calcula market share, analisa taxas de crescimento (CAGR), mapeia competitores com matrix de posicionamento, identifica barreiras de entrada e gera relatórios de inteligência competitiva.',category:'analysis',tags:['market','competition','growth','positioning','intelligence'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.94,install_command:'npx aifeast market-analyst',run_command:'npx aifeast run market-analyst'},
  {id:'investment_analyst',name:'Investment Analyst',slug:'investment-analyst',description:'Analisa investimentos com métricas financeiras: NPV, IRR, payback e risco.',long_description:'Analista de investimentos que calcula métricas financeiras (NPV, IRR, payback period, ROI), projeta fluxos de caixa, analisa cenários (bull, base, bear), avalia risco com simulação de Monte Carlo e recomenda alocação de portfólio.',category:'analysis',tags:['investment','npv','irr','portfolio','monte-carlo'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.94,install_command:'npx aifeast investment-analyst',run_command:'npx aifeast run investment-analyst'},
  {id:'financial_planner',name:'Financial Planner',slug:'financial-planner',description:'Planeja finanças pessoais e empresariais com projeções e cenários.',long_description:'Planejador financeiro que analisa receitas e despesas, projeta cenários futuros, define metas de economia, calcula independência financeira, otimiza alocação de investimentos e gera relatórios de saúde financeira.',category:'analysis',tags:['finance','planning','budget','projections','savings'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.92,install_command:'npx aifeast financial-planner',run_command:'npx aifeast run financial-planner'},
  {id:'healthcare_advisor',name:'Healthcare Advisor',slug:'healthcare-advisor',description:'Analisa dados de saúde com métricas vitais, tendências e recomendações.',long_description:'Conselheiro de saúde que analisa métricas vitais (pressão, glicose, colesterol, IMC), identifica tendências ao longo do tempo, compara com ranges normais, sugere mudanças de estilo de vida e alerta sobre valores que requerem atenção médica.',category:'analysis',tags:['health','vitals','trends','wellness','recommendations'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.93,install_command:'npx aifeast healthcare-advisor',run_command:'npx aifeast run healthcare-advisor'},
  {id:'legal_analyst',name:'Legal Analyst',slug:'legal-analyst',description:'Analisa documentos legais com identificação de riscos, cláusulas e conformidade.',long_description:'Analista legal que revisa contratos, identifica cláusulas problemáticas (indenização, não-concorrência, confidencialidade), verifica conformidade com legislação aplicável, compara com benchmarks de mercado e gera resumos executivos.',category:'analysis',tags:['legal','contracts','compliance','clauses','risk'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.94,install_command:'npx aifeast legal-analyst',run_command:'npx aifeast run legal-analyst'},
  {id:'educational_consultant',name:'Educational Consultant',slug:'educational-consultant',description:'Planeja jornadas de aprendizado com currículos personalizados e avaliações.',long_description:'Consultor educacional que cria planos de estudo personalizados por objetivo (carreira, certificação, hobby), sugere recursos (cursos, livros, projetos), define milestones de aprendizado, gera quizzes de auto-avaliação e ajusta plano baseado em progresso.',category:'analysis',tags:['education','learning','curriculum','assessment','personalized'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.92,install_command:'npx aifeast educational-consultant',run_command:'npx aifeast run educational-consultant'},
  {id:'psychologist_ai',name:'Psychologist AI',slug:'psychologist-ai',description:'Analisa padrões comportamentais com insights de psicologia e bem-estar.',long_description:'Analista comportamental que identifica padrões em textos e interações (estresse, ansiedade, motivação), aplica frameworks de psicologia positiva, sugere práticas de mindfulness e bem-estar, e sinaliza quando recomendar acompanhamento profissional. Não substitui terapia.',category:'analysis',tags:['psychology','behavior','wellbeing','mindfulness','patterns'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.91,install_command:'npx aifeast psychologist-ai',run_command:'npx aifeast run psychologist-ai'},
  {id:'math_tutor',name:'Math Tutor',slug:'math-tutor',description:'Ensina matemática com explicações passo a passo e exercícios graduais.',long_description:'Tutor de matemática que explica conceitos passo a passo (álgebra, cálculo, estatística, geometria), gera exercícios com dificuldade gradual, corrige erros comuns, usa analogias visuais e adapta ritmo ao nível do estudante.',category:'analysis',tags:['math','tutor','step-by-step','exercises','learning'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.93,install_command:'npx aifeast math-tutor',run_command:'npx aifeast run math-tutor'},
  {id:'science_communicator',name:'Science Communicator',slug:'science-communicator',description:'Traduz pesquisas científicas complexas em linguagem acessível ao público geral.',long_description:'Comunicador científico que traduz papers complexos em linguagem acessível, cria analogias intuitivas, gera visualizações explicativas, identifica implicações práticas da pesquisa e evita sensationalismo mantendo rigor científico.',category:'analysis',tags:['science','communication','simplification','research','outreach'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.92,install_command:'npx aifeast science-communicator',run_command:'npx aifeast run science-communicator'},
  {id:'sql_explorer',name:'SQL Explorer',slug:'sql-explorer',description:'Explora bancos SQL com schema introspection e queries geradas por IA.',long_description:'Explorador SQL que conecta a bancos, introspecta schemas automaticamente, gera queries em linguagem natural, explica execution plans, sugere índices e otimiza queries lentas com explicações didáticas.',category:'analysis',tags:['sql','exploration','schema','query-generation','optimization'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.94,install_command:'npx aifeast sql-explorer',run_command:'npx aifeast run sql-explorer'},
  {id:'chart_generator',name:'Chart Generator',slug:'chart-generator',description:'Gera gráficos a partir de dados com seleção automática do tipo ideal.',long_description:'Gerador de gráficos que analisa dados e seleciona o tipo ideal (barras, linhas, pizza, scatter, heatmap, box plot), gera visualizações em SVG/PNG, aplica paletas de cores acessíveis e adiciona annotations contextuais.',category:'analysis',tags:['charts','visualization','graphs','svg','data-viz'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.94,install_command:'npx aifeast chart-generator',run_command:'npx aifeast run chart-generator'},
  {id:'dashboard_builder',name:'Dashboard Builder',slug:'dashboard-builder',description:'Constrói dashboards interativos com KPIs, filtros e drill-down.',long_description:'Construtor de dashboards que agrega múltiplas fontes de dados, calcula KPIs em tempo real, implementa filtros interativos, drill-down de métricas, alertas visuais e exporta em PDF ou embed HTML.',category:'analysis',tags:['dashboard','kpis','interactive','filters','drill-down'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.95,install_command:'npx aifeast dashboard-builder',run_command:'npx aifeast run dashboard-builder'},
  {id:'metrics_calculator',name:'Metrics Calculator',slug:'metrics-calculator',description:'Calcula métricas de negócio: CAC, LTV, churn, MRR, NPS e growth rate.',long_description:'Calculador de métricas de negócio que processa dados brutos e retorna CAC, LTV, churn rate, MRR/ARR, NPS, growth rate, burn rate, runway e unit economics. Gera benchmarks setoriais e identifica métricas fora do range saudável.',category:'analysis',tags:['metrics','cac','ltv','churn','mrr'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.94,install_command:'npx aifeast metrics-calculator',run_command:'npx aifeast run metrics-calculator'},
  {id:'anomaly_detector',name:'Anomaly Detector',slug:'anomaly-detector',description:'Detecta anomalias em séries temporais com métodos estatísticos e ML.',long_description:'Detector de anomalias que aplica métodos estatísticos (Z-score, IQR) e ML (Isolation Forest, One-Class SVM) para identificar outliers em séries temporais. Classifica severidade, identifica causa raiz provável e alerta em tempo real.',category:'analysis',tags:['anomaly','detection','outliers','statistical','ml'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.95,install_command:'npx aifeast anomaly-detector',run_command:'npx aifeast run anomaly-detector'},
  {id:'correlation_analyzer',name:'Correlation Analyzer',slug:'correlation-analyzer',description:'Analisa correlações entre variáveis com Pearson, Spearman e causalidade.',long_description:'Analisador de correlações que calcula Pearson, Spearman e Kendall entre variáveis, identifica correlações espúrias, testa causalidade com métodos de Granger, gera heatmaps de correlação e explica resultados em linguagem natural.',category:'analysis',tags:['correlation','pearson','spearman','causality','heatmap'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.93,install_command:'npx aifeast correlation-analyzer',run_command:'npx aifeast run correlation-analyzer'},
  {id:'time_series_forecaster',name:'Time Series Forecaster',slug:'time-series-forecaster',description:'Faz forecasting com ARIMA, Prophet e redes neurais com intervalos de confiança.',long_description:'Forecasting de séries temporais que aplica ARIMA, SARIMA, Prophet e LSTM, detecta sazonalidade e tendência, gera previsões com intervalos de confiança, backtest accuracy e compara múltiplos modelos automaticamente.',category:'analysis',tags:['forecasting','arima','prophet','timeseries','neural'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.95,install_command:'npx aifeast time-series-forecaster',run_command:'npx aifeast run time-series-forecaster'},
  {id:'ab_test_analyzer',name:'A/B Test Analyzer',slug:'ab-test-analyzer',description:'Analisa resultados de A/B tests com significância estatística e power analysis.',long_description:'Analisador de A/B tests que calcula significância estatística, confidence intervals, effect sizes, power analysis, detecta peeking problem, sugere sample size mínimo e gera relatórios com recomendação clara (implementar, continuar teste, abandonar).',category:'analysis',tags:['ab-testing','significance','statistics','power','experiment'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.94,install_command:'npx aifeast ab-test-analyzer',run_command:'npx aifeast run ab-test-analyzer'},
  {id:'cohort_analyzer',name:'Cohort Analyzer',slug:'cohort-analyzer',description:'Analisa retenção por coorte com heatmaps de sobrevivência e lifetime value.',long_description:'Analisador de cohort que agrupa usuários por data de aquisição, calcula taxas de retenção por período, gera heatmaps visuais, projeta lifetime value por coorte e identifica fatores que correlacionam com maior retenção.',category:'analysis',tags:['cohort','retention','heatmap','ltv','survival'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.93,install_command:'npx aifeast cohort-analyzer',run_command:'npx aifeast run cohort-analyzer'},
  {id:'funnel_analyzer',name:'Funnel Analyzer',slug:'funnel-analyzer',description:'Analisa funis de conversão com drop-off por etapa e recomendações.',long_description:'Analisador de funis que mapeia jornadas de usuário, calcula taxas de conversão por etapa, identifica maiores pontos de drop-off, segmenta por dispositivo/geografia e sugere otimizações priorizadas por impacto estimado.',category:'analysis',tags:['funnel','conversion','dropoff','optimization','journey'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.93,install_command:'npx aifeast funnel-analyzer',run_command:'npx aifeast run funnel-analyzer'},
  {id:'segmentation_engine',name:'Segmentation Engine',slug:'segmentation-engine',description:'Segmenta usuários com clustering (K-means, DBSCAN) e personas automáticas.',long_description:'Engine de segmentação que aplica K-means, DBSCAN e hierarchical clustering para segmentar usuários por comportamento, gera personas automáticas com descrições, calcula tamanho de cada segmento e sugere estratégias de engagement por segmento.',category:'analysis',tags:['segmentation','clustering','kmeans','personas','behavior'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.94,install_command:'npx aifeast segmentation-engine',run_command:'npx aifeast run segmentation-engine'},
  {id:'attribution_modeler',name:'Attribution Modeler',slug:'attribution-modeler',description:'Modela atribuição de conversões com modelos multi-touch e Markov chains.',long_description:'Modelador de atribuição que compara modelos (last-click, first-click, linear, time-decay, position-based), aplica Markov chains para atribuição probabilística, calcula ROI por canal e sugere redistribuição de budget de marketing.',category:'analysis',tags:['attribution','multi-touch','markov','roi','marketing'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.93,install_command:'npx aifeast attribution-modeler',run_command:'npx aifeast run attribution-modeler'},
  {id:'code_analyzer',name:'Code Analyzer',slug:'code-analyzer',description:'Analisa código com métricas de complexidade, cobertura e dívida técnica.',long_description:'Analisador de código que calcula complexidade ciclomática, acoplamento, coesão, cobertura de testes, dívida técnica estimada, hotspots de bugs e gera relatórios de qualidade com comparações temporais.',category:'analysis',tags:['code','complexity','coverage','debt','quality'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.94,install_command:'npx aifeast code-analyzer',run_command:'npx aifeast run code-analyzer'},
  {id:'performance_profiler',name:'Performance Profiler',slug:'performance-profiler',description:'Profile aplicações com análise de CPU, memória, I/O e rede.',long_description:'Profiler de performance que captura traces de CPU, heap snapshots de memória, I/O blocking, chamadas de rede, gera flame graphs, identifica bottlenecks, sugere otimizações específicas e compara baseline vs otimizado.',category:'analysis',tags:['profiling','cpu','memory','flame-graph','bottleneck'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.95,install_command:'npx aifeast performance-profiler',run_command:'npx aifeast run performance-profiler'},
  {id:'architecture_reviewer',name:'Architecture Reviewer',slug:'architecture-reviewer',description:'Revisa arquiteturas de software com padrões, trade-offs e recomendações.',long_description:'Revisor de arquitetura que analisa diagramas e código, avalia aderência a padrões (SOLID, Clean Architecture, 12-Factor), identifica anti-patterns, sugere refatorações estruturais, avalia trade-offs e gera relatórios de maturidade arquitetural.',category:'analysis',tags:['architecture','review','patterns','solid','tradeoffs'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.95,install_command:'npx aifeast architecture-reviewer',run_command:'npx aifeast run architecture-reviewer'},
  {id:'complexity_assessor',name:'Complexity Assessor',slug:'complexity-assessor',description:'Avalia complexidade de sistemas com métricas de acoplamento e coesão.',long_description:'Avaliador de complexidade que calcula métricas de acoplamento afferent/efferent, instabilidade, abstração, distância da zona principal, identifica módulos problemáticos e sugere refatorações para melhorar manutenibilidade.',category:'analysis',tags:['complexity','coupling','cohesion','metrics','refactoring'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.93,install_command:'npx aifeast complexity-assessor',run_command:'npx aifeast run complexity-assessor'},
  {id:'tech_debt_calculator',name:'Tech Debt Calculator',slug:'tech-debt-calculator',description:'Calcula dívida técnica em horas/dias com priorização por impacto no negócio.',long_description:'Calculador de tech debt que identifica code smells, duplicações, falta de testes, dependências desatualizadas, estima esforço de correção em horas/dias, prioriza por impacto no negócio e gera roadmap de pagamento de dívida.',category:'analysis',tags:['tech-debt','estimation','prioritization','roadmap','quality'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.92,install_command:'npx aifeast tech-debt-calculator',run_command:'npx aifeast run tech-debt-calculator'},
  {id:'change_impact_analyzer',name:'Change Impact Analyzer',slug:'change-impact-analyzer',description:'Analisa impacto de mudanças de código com grafo de dependências.',long_description:'Analisador de impacto que constrói grafo de dependências do código, identifica todos os arquivos afetados por uma mudança, estima risco de regressão, sugere testes necessários e gera relatório de blast radius antes do merge.',category:'analysis',tags:['impact','dependencies','risk','regression','graph'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.93,install_command:'npx aifeast change-impact-analyzer',run_command:'npx aifeast run change-impact-analyzer'},
  {id:'dependency_mapper',name:'Dependency Mapper',slug:'dependency-mapper',description:'Mapeia todas as dependências de um projeto com versões e vulnerabilidades.',long_description:'Mapeador de dependências que extrai todas as libs de package.json, requirements.txt, go.mod, gera grafo de dependências diretas e transitivas, identifica versões desatualizadas, vulnerabilidades CVE e sugere upgrades seguros.',category:'analysis',tags:['dependencies','graph','versions','cve','mapping'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.94,install_command:'npx aifeast dependency-mapper',run_command:'npx aifeast run dependency-mapper'},
  {id:'api_usage_analyzer',name:'API Usage Analyzer',slug:'api-usage-analyzer',description:'Analisa padrões de uso de APIs com endpoints mais acessados e gargalos.',long_description:'Analisador de uso de APIs que processa logs de requests, identifica endpoints mais acessados, padrões de uso por cliente, gargalos de performance, taxa de erro por endpoint e gera relatórios de otimização com recomendações de caching.',category:'analysis',tags:['api','usage','logs','bottlenecks','optimization'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.93,install_command:'npx aifeast api-usage-analyzer',run_command:'npx aifeast run api-usage-analyzer'},
  {id:'log_pattern_detector',name:'Log Pattern Detector',slug:'log-pattern-detector',description:'Detecta padrões recorrentes em logs com clustering de mensagens.',long_description:'Detector de padrões em logs que agrupa mensagens similares com clustering, identifica padrões de erro recorrentes, correlaciona eventos temporais, detecta mudanças de padrão após deploys e gera alertas proativos.',category:'analysis',tags:['logs','patterns','clustering','correlation','alerts'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.93,install_command:'npx aifeast log-pattern-detector',run_command:'npx aifeast run log-pattern-detector'},
  {id:'error_categorizer',name:'Error Categorizer',slug:'error-categorizer',description:'Categoriza erros automaticamente com ML e sugere fixes baseados em histórico.',long_description:'Categorizador de erros que classifica erros por tipo (runtime, network, validation, auth), usa ML para agrupar erros similares, sugere fixes baseados em resoluções passadas, estima frequência de ocorrência e prioriza por impacto.',category:'analysis',tags:['errors','categorization','ml','fixes','history'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.92,install_command:'npx aifeast error-categorizer',run_command:'npx aifeast run error-categorizer'},
  {id:'root_cause_finder',name:'Root Cause Finder',slug:'root-cause-finder',description:'Identifica causa raiz de incidentes com análise de correlação temporal.',long_description:'Encontrador de root cause que analisa logs, métricas e deploys no período do incidente, correlaciona eventos temporais, identifica mudanças que precedem erros, gera timeline de incidentes e sugere causa raiz provável com nível de confiança.',category:'analysis',tags:['root-cause','incidents','correlation','timeline','debugging'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.94,install_command:'npx aifeast root-cause-finder',run_command:'npx aifeast run root-cause-finder'},
  {id:'sentiment_analyzer_pro',name:'Sentiment Analyzer Pro',slug:'sentiment-analyzer-pro',description:'Analisa sentimento de textos com 5 níveis e detecção de emoções específicas.',long_description:'Analisador de sentimento avançado que classifica em 5 níveis (muito negativo a muito positivo), detecta emoções específicas (alegria, raiva, medo, surpresa, tristeza), analisa por segmento de texto e gera relatórios de evolução temporal.',category:'analysis',tags:['sentiment','emotion','nlp','classification','analysis'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.95,install_command:'npx aifeast sentiment-analyzer-pro',run_command:'npx aifeast run sentiment-analyzer-pro'},
  {id:'topic_classifier',name:'Topic Classifier',slug:'topic-classifier',description:'Classifica textos por tópico com modelos de NLP e LDA topic modeling.',long_description:'Classificador de tópicos que aplica LDA topic modeling,BERT classification e TF-IDF para categorizar textos automaticamente. Gera distribuição de tópicos por documento, identifica temas emergentes e permite treinamento com dados customizados.',category:'analysis',tags:['topics','classification','lda','nlp','bert'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.94,install_command:'npx aifeast topic-classifier',run_command:'npx aifeast run topic-classifier'},
  {id:'entity_extractor',name:'Entity Extractor',slug:'entity-extractor',description:'Extrai entidades nomeadas (pessoas, lugares, organizações) de textos.',long_description:'Extractor de entidades que identifica e classifica Named Entities (PESSOA, LOCAL, ORGANIZAÇÃO, DATA, VALOR, PRODUTO), gera grafos de relacionamento entre entidades, calcula frequência e gera summaries temáticos por entidade.',category:'analysis',tags:['entities','ner','extraction','knowledge-graph','nlp'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.94,install_command:'npx aifeast entity-extractor',run_command:'npx aifeast run entity-extractor'},
  {id:'keyword_extractor',name:'Keyword Extractor',slug:'keyword-extractor',description:'Extrai keywords relevantes com TF-IDF, TextRank e RAKE.',long_description:'Extractor de keywords que aplica TF-IDF, TextRank e RAKE para identificar termos mais relevantes em textos. Gera rankings ponderados, filtra stopwords customizadas, agrupa keywords por similaridade e sugere tags para SEO.',category:'analysis',tags:['keywords','tf-idf','textrank','rake','seo'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.93,install_command:'npx aifeast keyword-extractor',run_command:'npx aifeast run keyword-extractor'},
  {id:'quality_scorer',name:'Quality Scorer',slug:'quality-scorer',description:'Avalia qualidade de textos com métricas de clareza, coesão e completude.',long_description:'Scorer de qualidade que avalia textos em múltiplas dimensões: clareza (legibilidade, vocabulário), coesão (transições, estrutura), completude (tópicos cobertos, profundidade), gera score composto e sugestões específicas de melhoria.',category:'analysis',tags:['quality','scoring','clarity','cohesion','completeness'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.92,install_command:'npx aifeast quality-scorer',run_command:'npx aifeast run quality-scorer'},
  {id:'bias_detector',name:'Bias Detector',slug:'bias-detector',description:'Detecta viés em textos: gênero, raça, idade, política e cultural.',long_description:'Detector de viés que analisa textos para viés de gênero, raça, idade, político e cultural. Identifica linguagem carregada, estereótipos, generalizações, sugere alternativas neutras e gera relatório de neutralidade com score.',category:'analysis',tags:['bias','fairness','diversity','language','neutrality'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.93,install_command:'npx aifeast bias-detector',run_command:'npx aifeast run bias-detector'},
  {id:'readability_assessor',name:'Readability Assessor',slug:'readability-assessor',description:'Avalia legibilidade com múltiplos índices e sugere simplificações.',long_description:'Avaliador de legibilidade que calcula Flesch-Kincaid, Gunning Fog, SMOG e Índice de Legibilidade Flesch em português. Identifica frases longas, palavras complexas, jargão excessivo e sugere simplificações para alcançar nível de leitura alvo.',category:'analysis',tags:['readability','flesch','gunning','simplification','accessibility'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.92,install_command:'npx aifeast readability-assessor',run_command:'npx aifeast run readability-assessor'},
  {id:'competitor_analyzer',name:'Competitor Analyzer',slug:'competitor-analyzer',description:'Analisa concorrentes com features, pricing, reviews e posicionamento.',long_description:'Analisador de concorrentes que compara features lado a lado, analisa pricing strategies, extrai insights de reviews de clientes, mapeia posicionamento de mercado com perceptual map e identifica gaps competitivos e oportunidades.',category:'analysis',tags:['competitors','comparison','pricing','positioning','reviews'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.94,install_command:'npx aifeast competitor-analyzer',run_command:'npx aifeast run competitor-analyzer'},
  {id:'swot_generator',name:'SWOT Generator',slug:'swot-generator',description:'Gera análises SWOT completas com fatores internos e externos.',long_description:'Gerador de análises SWOT que identifica Strengths, Weaknesses (internos), Opportunities e Threats (externos) de projetos/empresas. Prioriza fatores por impacto e probabilidade, gera matriz visual e sugere estratégias (SO, ST, WO, WT).',category:'analysis',tags:['swot','strategy','analysis','planning','matrix'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.92,install_command:'npx aifeast swot-generator',run_command:'npx aifeast run swot-generator'},
  {id:'data_quality_checker',name:'Data Quality Checker',slug:'data-quality-checker',description:'Verifica qualidade de dados com completude, consistência e validade.',long_description:'Checker de qualidade de dados que verifica completude (% valores nulos), consistência (formatos, ranges), unicidade (duplicatas), validade (constraints de negócio), atualidade dos dados e gera relatório de qualidade com score por dimensão.',category:'analysis',tags:['data-quality','completeness','consistency','validity','duplicates'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.93,install_command:'npx aifeast data-quality-checker',run_command:'npx aifeast run data-quality-checker'},
  {id:'survey_analyzer',name:'Survey Analyzer',slug:'survey-analyzer',description:'Analisa respostas de surveys com estatísticas, correlações e segmentação.',long_description:'Analisador de surveys que processa respostas de questionários, calcula estatísticas descritivas por pergunta, identifica correlações entre respostas, segmenta por demografia, gera NPS/CSAT scores e visualizações de Likert scales.',category:'analysis',tags:['surveys','statistics','nps','csat','segmentation'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.93,install_command:'npx aifeast survey-analyzer',run_command:'npx aifeast run survey-analyzer'}
];

console.log(`\n=== BLOCO 4/5 — ANALYSIS (${block4.length} skills) ===`);
await insertSkills(block4, 'BLOCK 4: ANALYSIS');
