// Bloco 3/5 — AUTOMATION (50 skills únicas)
import fs from 'fs';

const SUPABASE_URL = 'https://liqutcjzzrqstivvfele.supabase.co';
const SUPABASE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxpcXV0Y2p6enJxc3RpdnZmZWxlIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3NTQ5ODAzNiwiZXhwIjoyMDkxMDc0MDM2fQ.CEwxEeOB2CoAF0JyreovFYhU4Ibc03np8RgU6B6SiP0';

async function fetchExistingSlugs() {
  const res = await fetch(`${SUPABASE_URL}/rest/v1/skills?select=slug`, {
    headers: { 'apikey': SUPABASE_KEY, 'Authorization': `Bearer ${SUPABASE_KEY}` }
  });
  const data = await res.json();
  return new Set(data.map(s => s.slug));
}

async function insertSkills(skills, blockName) {
  const existingSlugs = await fetchExistingSlugs();
  const conflicts = skills.filter(s => existingSlugs.has(s.slug));
  if (conflicts.length > 0) {
    console.error(`❌ CONFLICTS in ${blockName} (${conflicts.length}):`);
    conflicts.forEach(s => console.error(`   - ${s.slug}`));
    process.exit(1);
  }
  console.log(`✅ No slug conflicts for ${blockName}.\n`);

  let inserted = 0;
  let skipped = 0;

  for (let i = 0; i < skills.length; i += 10) {
    const batch = skills.slice(i, i + 10);
    const res = await fetch(`${SUPABASE_URL}/rest/v1/skills`, {
      method: 'POST',
      headers: {
        'apikey': SUPABASE_KEY,
        'Authorization': `Bearer ${SUPABASE_KEY}`,
        'Content-Type': 'application/json',
        'Prefer': 'resolution=merge-duplicates'
      },
      body: JSON.stringify(batch)
    });

    if (res.ok || res.status === 201) {
      inserted += batch.length;
      console.log(`  ✅ Batch ${Math.floor(i/10)+1}: ${batch.length} skills inserted`);
    } else {
      let batchInserted = 0;
      for (const skill of batch) {
        const r = await fetch(`${SUPABASE_URL}/rest/v1/skills`, {
          method: 'POST',
          headers: {
            'apikey': SUPABASE_KEY,
            'Authorization': `Bearer ${SUPABASE_KEY}`,
            'Content-Type': 'application/json',
            'Prefer': 'resolution=merge-duplicates'
          },
          body: JSON.stringify([skill])
        });
        if (r.ok || r.status === 201) batchInserted++;
        else skipped++;
      }
      inserted += batchInserted;
      console.log(`  ⚠️  Batch ${Math.floor(i/10)+1}: ${batchInserted} inserted, ${batch.length - batchInserted} skipped`);
    }
  }

  console.log(`\n=== ${blockName} RESULT ===`);
  console.log(`Total attempted: ${skills.length}`);
  console.log(`Total inserted: ${inserted}`);
  console.log(`Total skipped: ${skipped}`);
  return { inserted, skipped };
}

// ==================== BLOCK 3: AUTOMATION ====================
const block3 = [
  {id:'web_scraper_pro',name:'Web Scraper Pro',slug:'web-scraper-pro',description:'Extrai dados de sites com handling de JS, paginação, CAPTCHAs e proxies.',long_description:'Scraper avançado que navega páginas com JavaScript rendering (Puppeteer, Playwright), lida com paginação infinita, resolve CAPTCHAs simples, usa proxy rotation, extrai dados estruturados e exporta em JSON/CSV. Respeita robots.txt e rate limits.',category:'automation',tags:['scraping','puppeteer','proxy','extraction','data'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.95,install_command:'npx aifeast web-scraper-pro',run_command:'npx aifeast run web-scraper-pro'},
  {id:'browser_automator',name:'Browser Automator',slug:'browser-automator',description:'Automatiza tarefas de navegador: preenchimento de formulários, clicks e navegação.',long_description:'Automatizador de browser que executa fluxos completos: login em sites, preenchimento de formulários, clicks sequenciais, screenshots, download de arquivos e extração de dados. Usa Playwright para automação headless com retry e error handling.',category:'automation',tags:['browser','playwright','automation','forms','headless'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.94,install_command:'npx aifeast browser-automator',run_command:'npx aifeast run browser-automator'},
  {id:'google_maps_connector',name:'Google Maps Connector',slug:'google-maps-connector',description:'Conecta à API do Google Maps para geocoding, rotas, places e distância.',long_description:'Conector do Google Maps que executa geocoding (endereço ↔ coordenadas), calcula rotas otimizadas, busca lugares próximos (places API), calcula matrizes de distância e tempo, e gera mapas estáticos para relatórios.',category:'automation',tags:['maps','geocoding','routes','places','google-api'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.93,install_command:'npx aifeast google-maps-connector',run_command:'npx aifeast run google-maps-connector'},
  {id:'postgresql_query_engine',name:'PostgreSQL Query Engine',slug:'postgresql-query-engine',description:'Executa queries read-only em bancos PostgreSQL com schema introspection.',long_description:'Engine de queries PostgreSQL que conecta a bancos, introspecta schemas (tabelas, colunas, tipos, constraints), executa queries read-only seguras, formata resultados em tabelas/JSON/CSV e gera explicações de execution plans.',category:'automation',tags:['postgresql','sql','database','read-only','query'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.95,install_command:'npx aifeast postgresql-query-engine',run_command:'npx aifeast run postgresql-query-engine'},
  {id:'redis_manager',name:'Redis Manager',slug:'redis-manager',description:'Gerencia caches Redis: set, get, TTL, pub/sub e monitoramento de memória.',long_description:'Gerenciador de Redis que executa operações de cache (SET, GET, DEL), configura TTLs inteligentes, gerencia pub/sub channels, monitora uso de memória, identifica keys expiradas e otimiza estratégias de eviction.',category:'automation',tags:['redis','cache','pubsub','memory','key-value'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.93,install_command:'npx aifeast redis-manager',run_command:'npx aifeast run redis-manager'},
  {id:'slack_bot_builder',name:'Slack Bot Builder',slug:'slack-bot-builder',description:'Cria bots Slack com slash commands, interactive buttons e workflows.',long_description:'Construtor de bots Slack que implementa slash commands, interactive buttons e menus, message shortcuts, workflows automatizados, notificações de CI/CD e integrações com APIs externas. Usa Bolt framework e gerencia permissões de OAuth.',category:'automation',tags:['slack','bot','slash-command','workflow','notifications'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.94,install_command:'npx aifeast slack-bot-builder',run_command:'npx aifeast run slack-bot-builder'},
  {id:'gmail_automator',name:'Gmail Automator',slug:'gmail-automator',description:'Automatiza emails Gmail: envio em massa, templates, filtros e respostas.',long_description:'Automatizador de Gmail que envia emails em massa com personalização, aplica templates profissionais, configura filtros e labels automáticos, gera respostas inteligentes baseadas no contexto e agenda envios programados.',category:'automation',tags:['gmail','email','automation','templates','scheduling'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.93,install_command:'npx aifeast gmail-automator',run_command:'npx aifeast run gmail-automator'},
  {id:'calendar_scheduler',name:'Calendar Scheduler',slug:'calendar-scheduler',description:'Gerencia agendas do Google Calendar: cria eventos, encontra slots livres e reminders.',long_description:'Agendador de calendário que cria eventos no Google Calendar, encontra slots livres entre participantes, configura reminders automáticos, sincroniza fusos horários, gera convites com links de videoconferência e envia follow-ups pós-reunião.',category:'automation',tags:['calendar','scheduling','google','meetings','reminders'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.92,install_command:'npx aifeast calendar-scheduler',run_command:'npx aifeast run calendar-scheduler'},
  {id:'jira_ticket_creator',name:'Jira Ticket Creator',slug:'jira-ticket-creator',description:'Cria tickets Jira com descrição estruturada, estimativas e assignees.',long_description:'Criador de tickets Jira que gera issues com descrições estruturadas (contexto, steps to reproduce, expected behavior), estimativas de story points, assignees automáticos por componente, labels e integração com sprints ativos.',category:'automation',tags:['jira','tickets','agile','sprint','issue-tracking'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.92,install_command:'npx aifeast jira-ticket-creator',run_command:'npx aifeast run jira-ticket-creator'},
  {id:'zapier_connector',name:'Zapier Connector',slug:'zapier-connector',description:'Conecta apps via Zapier com triggers, actions e multi-step Zaps.',long_description:'Conector Zapier que cria Zaps automatizados com triggers (webhook, schedule, email), actions (criar registro, enviar notificação, atualizar planilha) e multi-step workflows. Gera configurações de Zaps em formato importável.',category:'automation',tags:['zapier','integration','triggers','actions','workflows'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.91,install_command:'npx aifeast zapier-connector',run_command:'npx aifeast run zapier-connector'},
  {id:'webhook_dispatcher',name:'Webhook Dispatcher',slug:'webhook-dispatcher',description:'Dispara webhooks para múltiplos endpoints com retry, assinatura e logging.',long_description:'Dispatcher de webhooks que envia payloads para múltiplos endpoints simultaneamente, verifica assinaturas HMAC, implementa retry com exponential backoff, dead letter queue para falhas persistentes e log estruturado de cada dispatch.',category:'automation',tags:['webhooks','dispatch','retry','hmac','logging'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.94,install_command:'npx aifeast webhook-dispatcher',run_command:'npx aifeast run webhook-dispatcher'},
  {id:'cron_manager',name:'Cron Manager',slug:'cron-manager',description:'Gerencia jobs cron com agendamento visual, monitoring e alertas de falha.',long_description:'Gerenciador de cron jobs que agenda tarefas com expressões cron visuais, monitora execuções em tempo real, alerta sobre falhas via Slack/email, previne overlapping executions, implementa distributed locking e mantém histórico com métricas de duração.',category:'automation',tags:['cron','scheduling','monitoring','alerts','locking'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.93,install_command:'npx aifeast cron-manager',run_command:'npx aifeast run cron-manager'},
  {id:'event_listener',name:'Event Listener',slug:'event-listener',description:'Ouve e reage a eventos de sistemas (GitHub, Stripe, Slack) com handlers.',long_description:'Listener de eventos que se conecta a streams de eventos (GitHub webhooks, Stripe events, Slack events), filtra por tipo de evento, executa handlers customizados, garante processamento exactly-once e gera métricas de throughput.',category:'automation',tags:['events','webhooks','handlers','streaming','reactive'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.93,install_command:'npx aifeast event-listener',run_command:'npx aifeast run event-listener'},
  {id:'workflow_orchestrator',name:'Workflow Orchestrator',slug:'workflow-orchestrator',description:'Orquestra workflows complexos com DAGs, retries e parallel execution.',long_description:'Orquestrador de workflows que executa pipelines complexos com Directed Acyclic Graphs (DAGs), paralelismo automático onde não há dependências, retry inteligente por tipo de erro, timeouts configuráveis e dashboard de execução em tempo real.',category:'automation',tags:['workflow','orchestration','dag','parallel','pipeline'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.95,install_command:'npx aifeast workflow-orchestrator',run_command:'npx aifeast run workflow-orchestrator'},
  {id:'api_rate_limiter_pro',name:'API Rate Limiter Pro',slug:'api-rate-limiter-pro',description:'Implementa rate limiting distribuído com Redis, token bucket e sliding window.',long_description:'Rate limiter distribuído que implementa algoritmos de token bucket, sliding window log e fixed window. Integra com Redis para state compartilhado entre instâncias, define quotas por usuário/plano, retorna headers X-RateLimit e configura throttling progressivo.',category:'automation',tags:['rate-limiting','redis','token-bucket','throttling','distributed'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.94,install_command:'npx aifeast api-rate-limiter-pro',run_command:'npx aifeast run api-rate-limiter-pro'},
  {id:'queue_manager',name:'Queue Manager',slug:'queue-manager',description:'Gerencia filas de mensagens com RabbitMQ/SQS: enqueue, dequeue e DLQ.',long_description:'Gerenciador de filas que conecta a RabbitMQ ou AWS SQS, gerencia enqueue/dequeue com prioridade, configura dead letter queues para mensagens falhas, monitora depth de filas, implementa consumer groups e garante delivery at-least-once.',category:'automation',tags:['queue','rabbitmq','sqs','messaging','dlq'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.94,install_command:'npx aifeast queue-manager',run_command:'npx aifeast run queue-manager'},
  {id:'batch_processor',name:'Batch Processor',slug:'batch-processor',description:'Processa grandes volumes de dados em batches com chunking e parallelismo.',long_description:'Processador de batches que divide grandes datasets em chunks gerenciáveis, processa em paralelo com worker pools, reporta progresso em tempo real, implementa checkpoint para resume após falhas e agrega resultados finais.',category:'automation',tags:['batch','processing','chunking','parallel','checkpoint'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.93,install_command:'npx aifeast batch-processor',run_command:'npx aifeast run batch-processor'},
  {id:'data_sync_agent',name:'Data Sync Agent',slug:'data-sync-agent',description:'Sincroniza dados entre bancos/APIs com detecção de conflitos e CDC.',long_description:'Agente de sincronização que replica dados entre bancos e APIs com Change Data Capture (CDC), detecta conflitos de escrita, resolve com estratégias configuráveis (last-write-wins, merge, manual), mantém audit log e garante consistência eventual.',category:'automation',tags:['sync','cdc','replication','conflict','consistency'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.94,install_command:'npx aifeast data-sync-agent',run_command:'npx aifeast run data-sync-agent'},
  {id:'file_organizer',name:'File Organizer',slug:'file-organizer',description:'Organiza diretórios automaticamente por tipo, data ou tags customizadas.',long_description:'Organizador de arquivos que escaneia diretórios, classifica por tipo (PDF, imagem, código), data de criação ou regras customizadas (regex), move para estrutura hierárquica, renomeia com padrões consistentes e gera relatório de organização.',category:'automation',tags:['files','organization','filesystem','rename','cleanup'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.91,install_command:'npx aifeast file-organizer',run_command:'npx aifeast run file-organizer'},
  {id:'spreadsheet_automator',name:'Spreadsheet Automator',slug:'spreadsheet-automator',description:'Automatiza Google Sheets: leitura, escrita, fórmulas e dashboards.',long_description:'Automatizador de planilhas que conecta ao Google Sheets, lê/escreve dados em massa, aplica fórmulas complexas, gera gráficos e dashboards automáticos, configura triggers de atualização e exporta em PDF/CSV.',category:'automation',tags:['sheets','google','spreadsheets','formulas','dashboards'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.93,install_command:'npx aifeast spreadsheet-automator',run_command:'npx aifeast run spreadsheet-automator'},
  {id:'pdf_generator',name:'PDF Generator',slug:'pdf-generator',description:'Gera PDFs profissionais com templates, gráficos e tabelas de dados.',long_description:'Gerador de PDFs que cria documentos profissionais a partir de templates, inclui tabelas formatadas, gráficos (Chart.js), headers/footers, numeração de páginas, bookmarks e links clicáveis. Suporta invoices, relatórios e certificados.',category:'automation',tags:['pdf','generation','templates','reports','invoices'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.94,install_command:'npx aifeast pdf-generator',run_command:'npx aifeast run pdf-generator'},
  {id:'image_processor',name:'Image Processor',slug:'image-processor',description:'Processa imagens: redimensiona, comprime, converte formatos e aplica filtros.',long_description:'Processador de imagens que redimensiona mantendo aspect ratio, comprime com qualidade configurável (WebP, AVIF, JPEG), converte entre formatos, aplica filtros (blur, sharpen, grayscale), gera thumbnails e watermarks automáticos.',category:'automation',tags:['images','resize','compress','convert','filters'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.93,install_command:'npx aifeast image-processor',run_command:'npx aifeast run image-processor'},
  {id:'video_transcoder',name:'Video Transcoder',slug:'video-transcoder',description:'Transcode vídeos para múltiplos formatos e resoluções com FFmpeg.',long_description:'Transcoder de vídeos que converte entre formatos (MP4, WebM, MOV), gera múltiplas resoluções (1080p, 720p, 480p), otimiza bitrate, extrai thumbnails, gera legendas SRT a partir de áudio e cria clips automáticos.',category:'automation',tags:['video','transcoding','ffmpeg','encoding','subtitles'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.94,install_command:'npx aifeast video-transcoder',run_command:'npx aifeast run video-transcoder'},
  {id:'audio_transcriber',name:'Audio Transcriber',slug:'audio-transcriber',description:'Transcreve áudio para texto com timestamps e identificação de falantes.',long_description:'Transcritor de áudio que converte fala em texto com timestamps precisos, identifica falantes múltiplos (diarization), detecta idioma automaticamente, gera legendas SRT/VTT e suporta áudio em 20+ idiomas.',category:'automation',tags:['audio','transcription','speech-to-text','timestamps','diarization'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.95,install_command:'npx aifeast audio-transcriber',run_command:'npx aifeast run audio-transcriber'},
  {id:'rss_feed_aggregator',name:'RSS Feed Aggregator',slug:'rss-feed-aggregator',description:'Agrega múltiplos feeds RSS com deduplicação, categorização e alertas.',long_description:'Agregador de RSS feeds que monitora múltiplas fontes, deduplica artigos similares, categoriza por tópico usando NLP, gera newsletters automáticas, alerta sobre breaking news e exporta em JSON/Markdown.',category:'automation',tags:['rss','aggregation','feeds','news','deduplication'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.92,install_command:'npx aifeast rss-feed-aggregator',run_command:'npx aifeast run rss-feed-aggregator'},
  {id:'form_filler',name:'Form Filler',slug:'form-filler',description:'Preenche formulários web automaticamente com dados estruturados.',long_description:'Preenchedor de formulários que automatiza inputs em forms web, valida campos antes do submit, lida com CAPTCHAs simples, preenche múltiplos forms em sequência e exporta confirmações/screenshot de sucesso.',category:'automation',tags:['forms','automation','input','validation','captcha'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.91,install_command:'npx aifeast form-filler',run_command:'npx aifeast run form-filler'},
  {id:'report_generator',name:'Report Generator',slug:'report-generator',description:'Gera relatórios automáticos com dados, gráficos e insights acionáveis.',long_description:'Gerador de relatórios que agrega dados de múltiplas fontes (APIs, bancos, CSVs), gera gráficos (barras, linhas, pizza), calcula KPIs, identifica tendências e anomalias, e exporta em PDF, HTML ou apresentação.',category:'automation',tags:['reports','charts','kpis','insights','automation'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.94,install_command:'npx aifeast report-generator',run_command:'npx aifeast run report-generator'},
  {id:'meeting_summarizer',name:'Meeting Summarizer',slug:'meeting-summarizer',description:'Resuma reuniões gravadas com transcrição, decisões e action items.',long_description:'Resumidor de reuniões que transcreve áudio, identifica participantes, extrai decisões-chave, lista action items com responsáveis e prazos, gera minutes formatados e envia por email automaticamente.',category:'automation',tags:['meetings','summary','transcription','actions','minutes'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.94,install_command:'npx aifeast meeting-summarizer',run_command:'npx aifeast run meeting-summarizer'},
  {id:'task_tracker',name:'Task Tracker',slug:'task-tracker',description:'Rastreia tarefas entre ferramentas (Jira, Trello, GitHub) com dashboard unificado.',long_description:'Rastreador de tarefas que sincroniza entre Jira, Trello, GitHub Projects e Notion. Cria dashboard unificado, alerta sobre deadlines próximos, identifica blockers, gera métricas de velocity e sugere redistribuição de workload.',category:'automation',tags:['tasks','tracking','jira','trello','dashboard'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.92,install_command:'npx aifeast task-tracker',run_command:'npx aifeast run task-tracker'},
  {id:'email_auto_responder',name:'Email Auto-Responder',slug:'email-auto-responder',description:'Responde emails automaticamente com IA contextual e regras de escalonamento.',long_description:'Auto-responder de emails que analisa contexto, gera respostas inteligentes personalizadas, classifica prioridade (urgente, normal, spam), encaminha para humanos quando necessário, aprende com correções e mantém tom consistente.',category:'automation',tags:['email','auto-reply','ai','classification','escalation'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.93,install_command:'npx aifeast email-auto-responder',run_command:'npx aifeast run email-auto-responder'},
  {id:'data_entry_automator',name:'Data Entry Automator',slug:'data-entry-automator',description:'Automatiza entrada de dados entre sistemas com validação e logging.',long_description:'Automatizador de data entry que transfere dados entre sistemas (ERP → CRM, planilha → banco), valida formatos e constraints, loga cada operação, implementa rollback em caso de erro e gera relatório de audit trail.',category:'automation',tags:['data-entry','validation','erp','crm','audit'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.92,install_command:'npx aifeast data-entry-automator',run_command:'npx aifeast run data-entry-automator'},
  {id:'spreadsheet_formatter',name:'Spreadsheet Formatter',slug:'spreadsheet-formatter',description:'Formata planilhas automaticamente com estilos, fórmulas e validações.',long_description:'Formatador de planilhas que aplica estilos consistentes (cores, bordas, fontes), insere fórmulas complexas, configura validação de dados, cria conditional formatting, congela headers e gera templates reutilizáveis.',category:'automation',tags:['sheets','formatting','formulas','validation','templates'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.91,install_command:'npx aifeast spreadsheet-formatter',run_command:'npx aifeast run spreadsheet-formatter'},
  {id:'cloud_backup_manager',name:'Cloud Backup Manager',slug:'cloud-backup-manager',description:'Gerencia backups na nuvem com agendamento, criptografia e restauração.',long_description:'Gerenciador de backups que agenda backups automáticos (diário, semanal, mensal), cripta dados em trânsito e repouso, testa restaurações periodicamente, monitora integridade de backups e alerta sobre falhas ou storage cheio.',category:'automation',tags:['backup','cloud','encryption','restore','scheduling'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.94,install_command:'npx aifeast cloud-backup-manager',run_command:'npx aifeast run cloud-backup-manager'},
  {id:'deploy_automator',name:'Deploy Automator',slug:'deploy-automator',description:'Automatiza deploys com blue-green, canary e rollback automático.',long_description:'Automatizador de deploys que executa estratégias de blue-green deployment, canary releases com métricas de saúde, rollback automático se error rate subir, health checks pós-deploy e notificações de sucesso/falha.',category:'automation',tags:['deploy','blue-green','canary','rollback','ci-cd'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.95,install_command:'npx aifeast deploy-automator',run_command:'npx aifeast run deploy-automator'},
  {id:'infrastructure_provisioner',name:'Infrastructure Provisioner',slug:'infrastructure-provisioner',description:'Provisiona infraestrutura cloud com Terraform, CloudFormation ou Pulumi.',long_description:'Provisionador de infraestrutura que gera código IaC (Terraform, CloudFormation, Pulumi) a partir de descrições em linguagem natural, valida configurações antes do apply, estima custos mensais e gera diagramas de arquitetura.',category:'automation',tags:['infrastructure','terraform','provisioning','cloud','iac'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.94,install_command:'npx aifeast infrastructure-provisioner',run_command:'npx aifeast run infrastructure-provisioner'},
  {id:'monitoring_configurator',name:'Monitoring Configurator',slug:'monitoring-configurator',description:'Configura monitoring com Prometheus, Grafana, alerts e dashboards.',long_description:'Configurador de monitoring que setup Prometheus metrics, cria dashboards Grafana customizados, define alertas com thresholds inteligentes, configura PagerDuty/Slack notifications e gera runbooks para incidentes comuns.',category:'automation',tags:['monitoring','prometheus','grafana','alerts','dashboards'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.93,install_command:'npx aifeast monitoring-configurator',run_command:'npx aifeast run monitoring-configurator'},
  {id:'alert_manager',name:'Alert Manager',slug:'alert-manager',description:'Gerencia alertas com deduplicação, agrupamento e escalonamento inteligente.',long_description:'Gerenciador de alertas que deduplica alertas similares, agrupa por serviço/severidade, escalona automaticamente se não respondido, gera post-mortems de incidentes e analisa tendências de alertas para identificar problemas crônicos.',category:'automation',tags:['alerts','deduplication','escalation','incidents','postmortem'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.92,install_command:'npx aifeast alert-manager',run_command:'npx aifeast run alert-manager'},
  {id:'log_rotator',name:'Log Rotator',slug:'log-rotator',description:'Gerencia rotação de logs com compressão, retenção e arquivamento.',long_description:'Rotacionador de logs que configura rotação por tamanho ou tempo, comprime logs antigos (gzip, zstd), define políticas de retenção, arquiva em cold storage (S3 Glacier) e limpa logs expirados automaticamente.',category:'automation',tags:['logs','rotation','compression','retention','archival'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.91,install_command:'npx aifeast log-rotator',run_command:'npx aifeast run log-rotator'},
  {id:'ssl_cert_manager',name:'SSL Cert Manager',slug:'ssl-cert-manager',description:'Gerencia certificados SSL: renovação automática via Let\'s Encrypt e monitoramento.',long_description:'Gerenciador de certificados SSL que automatiza emissão e renovação via Let\'s Encrypt (ACME), monitora expiração, alerta 30/14/7 dias antes, verifica chain of trust e atualiza load balancers automaticamente.',category:'automation',tags:['ssl','certificates','letsencrypt','acme','renewal'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.94,install_command:'npx aifeast ssl-cert-manager',run_command:'npx aifeast run ssl-cert-manager'},
  {id:'dns_manager',name:'DNS Manager',slug:'dns-manager',description:'Gerencia registros DNS com propagação automática e health checks.',long_description:'Gerenciador de DNS que cria/atualiza registros (A, AAAA, CNAME, MX, TXT), verifica propagação global, configura health checks com failover automático, gerencia zonas DNS e implementa DNSSEC para segurança.',category:'automation',tags:['dns','records','propagation','health-checks','dnssec'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.93,install_command:'npx aifeast dns-manager',run_command:'npx aifeast run dns-manager'},
  {id:'container_orchestrator',name:'Container Orchestrator',slug:'container-orchestrator',description:'Orquestra containers Docker/K8s com scaling, networking e storage.',long_description:'Orquestrador de containers que gerencia deployments Kubernetes, configura auto-scaling (HPA/VPA), define network policies, gerena persistent volumes, implementa service mesh e monitora health de pods.',category:'automation',tags:['containers','kubernetes','docker','scaling','orchestration'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.95,install_command:'npx aifeast container-orchestrator',run_command:'npx aifeast run container-orchestrator'},
  {id:'git_release_manager',name:'Git Release Manager',slug:'git-release-manager',description:'Gerencia releases Git com versionamento semântico, changelogs e tags.',long_description:'Gerenciador de releases Git que aplica versionamento semântico automático (semver), gera changelogs de conventional commits, cria tags annotated, prepara release notes e configura CI para publicação em registries.',category:'automation',tags:['git','releases','semver','changelog','tags'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.93,install_command:'npx aifeast git-release-manager',run_command:'npx aifeast run git-release-manager'},
  {id:'database_scaler',name:'Database Scaler',slug:'database-scaler',description:'Escala bancos de dados com read replicas, sharding e connection pooling.',long_description:'Scaler de bancos que configura read replicas automáticas, implementa sharding horizontal, gerencia connection pools (PgBouncer, ProxySQL), monitora query performance e sugere otimizações de scale-up/scale-out.',category:'automation',tags:['database','scaling','replicas','sharding','pooling'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.94,install_command:'npx aifeast database-scaler',run_command:'npx aifeast run database-scaler'},
  {id:'cdn_configurator',name:'CDN Configurator',slug:'cdn-configurator',description:'Configura CDNs com cache rules, edge computing e otimização de assets.',long_description:'Configurador de CDN que setup CloudFlare/AWS CloudFront, define cache rules por tipo de conteúdo, configura edge functions, otimiza assets (minify, compress, image optimization), implementa WAF rules e monitora hit rates.',category:'automation',tags:['cdn','cloudflare','cache','edge','optimization'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.93,install_command:'npx aifeast cdn-configurator',run_command:'npx aifeast run cdn-configurator'},
  {id:'cost_optimizer',name:'Cost Optimizer',slug:'cost-optimizer',description:'Otimiza custos de cloud identificando recursos ociosos e right-sizing.',long_description:'Otimizador de custos que analisa uso de cloud (AWS, GCP, Azure), identifica recursos ociosos ou underutilized, sugere right-sizing de instâncias, recomenda reserved instances/savings plans, detecta storage não usado e gera relatórios de economia.',category:'automation',tags:['cost','optimization','cloud','right-sizing','savings'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.94,install_command:'npx aifeast cost-optimizer',run_command:'npx aifeast run cost-optimizer'},
  {id:'compliance_checker',name:'Compliance Checker',slug:'compliance-checker',description:'Verifica conformidade com LGPD, GDPR, SOC2 e gera relatórios de auditoria.',long_description:'Checker de compliance que audita sistemas contra frameworks LGPD, GDPR, SOC2, ISO 27001, identifica gaps de conformidade, gera relatórios detalhados com evidências, sugere remediation e monitora continuous compliance.',category:'automation',tags:['compliance','lgpd','gdpr','soc2','audit'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.95,install_command:'npx aifeast compliance-checker',run_command:'npx aifeast run compliance-checker'},
  {id:'notification_dispatcher',name:'Notification Dispatcher',slug:'notification-dispatcher',description:'Dispara notificações multi-canal (email, SMS, push, Slack) com templates.',long_description:'Dispatcher de notificações que envia por múltiplos canais (email, SMS, push, Slack, WhatsApp), gerencia templates personalizados, respeita preferências do usuário, implementa rate limiting por canal e gera métricas de delivery.',category:'automation',tags:['notifications','multi-channel','templates','delivery','messaging'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.93,install_command:'npx aifeast notification-dispatcher',run_command:'npx aifeast run notification-dispatcher'},
  {id:'api_gateway_builder',name:'API Gateway Builder',slug:'api-gateway-builder',description:'Constrói API gateways com routing, auth, rate limiting e logging.',long_description:'Construtor de API gateways que configura routing inteligente, autenticação centralizada (JWT, OAuth2), rate limiting por consumidor, request/response transformation, logging estruturado, caching de respostas e circuit breaking.',category:'automation',tags:['api-gateway','routing','auth','rate-limiting','caching'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.95,install_command:'npx aifeast api-gateway-builder',run_command:'npx aifeast run api-gateway-builder'},
  {id:'graphql_federation_setup',name:'GraphQL Federation Setup',slug:'graphql-federation-setup',description:'Configura GraphQL federation com multi-graph composition e gateway routing.',long_description:'Setup de GraphQL federation que compõe multi-graph schemas, configura gateway routing entre subgraphs, gerencia entity resolution, implementa query planning otimizado e monitora performance federada.',category:'automation',tags:['graphql','federation','gateway','subgraphs','composition'],source:'manual',verified:true,is_active:true,risk_level:'low',validation_score:0.94,install_command:'npx aifeast graphql-federation-setup',run_command:'npx aifeast run graphql-federation-setup'}
];

console.log(`\n=== BLOCO 3/5 — AUTOMATION (${block3.length} skills) ===`);
await insertSkills(block3, 'BLOCK 3: AUTOMATION');
